FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/
COPY backend*.py /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

# Use a default command; will be overridden by docker-compose
CMD ["python", "backend1.py"]
